name: Sincronizar con repositorio original

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sincronizar fork
        env:
          GH_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          gh api --method POST \
            repos/${{ github.repository }}/merge-upstream \
            -f branch=main
